### Değişken Standardizasyonu (Veri Standardizasyonu)

*Değişken Standardizasyonu Nedir ? Değişken Standardizasyonu değişkenin kendi içindeki bilgi yapısının bozulmadan belirli bir standarta oturtulmasıdır. Değeri değişir,ama temsil ettiği yayılım ve dağılım bilgisi değişmez. Örneğin 10 değerinin veri setinde bir değişken içerisinde küçükten büyüğe doğru sıralandığında 80.sırada olduğunu varsayalım. Bu 10 değerinin bulunduğu değişken; standardizasyon işlemine tabi tutulduktan sonra değeri -1.5786859 gibi bir değer olacak. Fakat sıralama işlemi sonunda bu değer yine 80.sırada olacaktır. Değişkenin ortalama,medyan, standart sapma gibi değerleri değişecektir fakat bu değerin değişken içerisindeki yayılım ve dağılım bilgisi değişmeyecektir.*

In [2]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,5,6,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df = pd.DataFrame(
    {"V1" : V1,
     "V2" : V2,
     "V3" : V3}
)

df = df.astype(float)
df

,V1,V2,V3
0,1.0,7.0,6.0
1,3.0,7.0,12.0
2,5.0,5.0,5.0
3,6.0,8.0,6.0
4,7.0,12.0,14.0


#### Standardizasyon

In [4]:
from sklearn import preprocessing

In [5]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.27854301, -1.2094158 , -0.98198051],
       [ 0.74278135,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [6]:
df.mean()

V1    4.4
V2    7.8
V3    8.6
dtype: float64

#### Normalizasyon

In [7]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.57735027, 0.57735027, 0.57735027],
       [0.51449576, 0.68599434, 0.51449576],
       [0.35491409, 0.60842415, 0.70982818]])

#### Min - MaX Dönüşümü

In [8]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))

In [9]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [16.66666667, 10.        , 10.        ],
       [18.33333333, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])