## Bagged Trees (Model)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import BaggingRegressor
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
hit = pd.read_csv("hitters.csv")
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[["League", "Division", "NewLeague"]])
dms = dms.astype(int)
y = df["Salary"]
X_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis = 1).astype("float64")
X = pd.concat([X_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size = 0.25,
                                                    random_state = 42)

In [3]:
bag_model = BaggingRegressor(bootstrap_features = True)
bag_model.fit(X_train, y_train)

BaggingRegressor(bootstrap_features=True)

In [4]:
#olusturulan agac sayisi

In [5]:
bag_model.n_estimators

10

In [6]:
#agac detay

In [7]:
bag_model.estimators_

[DecisionTreeRegressor(random_state=175249080),
 DecisionTreeRegressor(random_state=1207406148),
 DecisionTreeRegressor(random_state=717308623),
 DecisionTreeRegressor(random_state=668729559),
 DecisionTreeRegressor(random_state=984429832),
 DecisionTreeRegressor(random_state=1341112025),
 DecisionTreeRegressor(random_state=892890504),
 DecisionTreeRegressor(random_state=193547943),
 DecisionTreeRegressor(random_state=582913826),
 DecisionTreeRegressor(random_state=1983757315)]

In [8]:
#her bir agacin ornek sayisi(hangi agacta hangi gozlem birimleri var?)

In [9]:
bag_model.estimators_samples_

[array([173, 177,  13,  85,  59,  73, 106, 172,  77, 196,  36, 150, 139,
         88,   7,  88,  31,  76,  12, 164,  60,  20, 166, 177,  98, 138,
        108,   2, 145, 135, 196,  34, 168, 122,  76,  65,  30,  42, 163,
         61, 170, 106,  47,   6,  41,  84,  19, 151,  92,  67, 123,  30,
        126, 159, 120, 193,   7, 144, 106,  19,  60, 149,  94, 104, 139,
        135, 165, 125, 190, 120,  41, 135, 147, 133, 185,  46, 189, 152,
        158,  71,  20, 190,  75, 189, 102, 160, 158,   3,  85, 188,  64,
         17,  75,  64, 134, 143, 173, 130, 163,  89, 155,  79,  25,  65,
        167,  49, 155, 117, 178,  14,  16,  42,  51, 118,  51,  96,  46,
         85, 185,  23, 163,   1, 186, 117,  32, 106,  68, 157, 129,  22,
         74,   5, 143, 162,  51,  90, 189, 112, 148,  23,  19, 173, 160,
        171,  34,  87,  88,  13,  45,  23,  58,  11,  61,  59,  85, 151,
         12, 123, 185,  46,  10,  65, 144, 120, 107, 178,  25, 101, 171,
         75,  69, 174, 126, 187,  14,  28,  76,   5

In [10]:
#her bir agacin kullandigi degiskenler

In [11]:
bag_model.estimators_features_

[array([16,  2,  4,  7, 15,  6, 15, 17, 15,  5, 17, 18, 11,  4,  1,  9,  6,
        10, 17], dtype=int32),
 array([ 4,  0,  1,  1,  9,  5,  9,  3, 15, 17,  5, 12,  5,  9,  4, 11, 11,
        14, 13], dtype=int32),
 array([15,  2,  1, 10, 18,  4,  8, 11,  9, 18,  2,  5, 13, 13,  9, 15,  4,
         6, 11], dtype=int32),
 array([ 3, 14,  6, 13, 16,  3,  0, 15, 11, 10, 13,  4, 13,  3, 12,  3,  6,
         2,  5], dtype=int32),
 array([ 8, 14,  2,  9,  4, 14,  1,  8, 12,  6, 13, 10,  0,  4,  4,  7,  9,
         1,  9], dtype=int32),
 array([17,  9,  7, 14,  1,  4,  3,  1,  7,  3,  5,  3, 10, 12,  0, 16, 14,
         0, 11], dtype=int32),
 array([ 8, 16, 16,  9, 16, 14, 11, 13,  8, 17, 12,  2,  3, 12, 17,  6,  6,
        11, 16], dtype=int32),
 array([ 7,  4,  4,  8, 12,  6, 10,  1, 18, 13,  2, 17,  4, 13, 12,  8,  6,
        14, 17], dtype=int32),
 array([ 2,  8, 12, 18,  4,  0,  3, 13,  7, 11,  0,  1, 15,  9, 11,  4, 10,
         5,  1], dtype=int32),
 array([ 3,  6,  0,  4, 12,  4, 18,  

## Tahmin

In [12]:
y_pred = bag_model.predict(X_test)

In [13]:
np.sqrt(mean_squared_error(y_test, y_pred))

np.float64(323.44801217316086)

*Yukarıdaki değer birnevi bütün ağaçların hata değerinin ortalaması. Bütün ağaçları tek tek kontrol edip senin tahminin nedir diye bir sorgu yapma şansımız da var. Kötü tahminci olan ağaçları tek tek inceleme şansımız var. Yani mevcut ağaçların herhangi birinin yaptığı hata değerini gözlemleyip kötü tahmin yapan ağaçlaro optimizasyon işlemleri uygulayabiliriz.*

In [14]:
sec_y_pred = bag_model.estimators_[1].fit(X_train, y_train).predict(X_test)

In [15]:
np.sqrt(mean_squared_error(y_test, sec_y_pred))

np.float64(513.9130707447545)

*Baya beceriksiz bir ağaca denk geldik !*

## Model Tuning

In [16]:
bag_model = BaggingRegressor(bootstrap_features = True)
bag_model.fit(X_train, y_train)

BaggingRegressor(bootstrap_features=True)

In [17]:
bag_params = {"n_estimators" : range(2, 20)}

In [18]:
bag_cv_model = GridSearchCV(bag_model, bag_params, cv = 10)

In [19]:
bag_cv_model.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=BaggingRegressor(bootstrap_features=True),
             param_grid={'n_estimators': range(2, 20)})

In [20]:
bag_cv_model.best_params_

{'n_estimators': 11}

In [21]:
#final model

In [22]:
tuned_bag_model = BaggingRegressor(n_estimators = 19, random_state = 45)

In [23]:
tuned_bag_model.fit(X_train, y_train)

BaggingRegressor(n_estimators=19, random_state=45)

In [24]:
#final test hatasi

In [25]:
y_pred = tuned_bag_model.predict(X_test)

In [26]:
np.sqrt(mean_squared_error(y_test, y_pred))

np.float64(331.6722259721113)